name: audio
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.6.0
  rxdart: ^0.27.7
  sqflite_sqlcipher: ^2.1.1+1
  path: ^1.8.3
  flutter_easyloading: ^3.0.5
  dio: ^5.1.2

  assets_audio_player:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audios/
    - assets/images/